### ISSUE TITLE
Malapad | Reviewer Feedback

### ISSUE THREAD

**Issue by Naoe-Adrian** [PUP-BSIT/exercise-13-avengears#11]
- Followed some coding guidelines and code requirements for the comment section, but it's not fully functioning.
- Unnecessary comments
- Use of `var` in variable declaration
- Unable to apply guard clause
- Sort button not functioning
- Their team is not able to properly add the Netlify link to the README file.
- He communicated and asked questions despite having a busy schedule that day.

**Comment by ssvillarosa** [comment]
Score 4/10

**Comment by Malapad** [comment]
Thank you po
